name: FHIR Package

on:
  push:
    branches:
      - main
      - dev
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-profiles:
    name: Build Profiles
    runs-on: ubuntu-latest
    container: hl7fhir/ig-publisher-base:latest
    steps:
      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: "18"
      - name: Install fsh-sushi
        run: npm install -g fsh-sushi@3.0.0-beta.1
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Download IG Publisher
        run: ./_updatePublisher.sh -y
      - name: Get FHIR packages
        uses: cybernop/get-fhir-packages@v1
      - run: ls -la
      - name: Build profiles
        run: ./_genonce.sh
      - name: Archive profile artifacts
        uses: actions/upload-artifact@v3
        with:
          name: package
          path: output/package.tgz
      - name: Archive generated pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: output

  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: build-profiles
    if: github.ref_name == 'dev'
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
